# cloudbuild.yaml
#
# This file defines the steps for the Continuous Integration/Continuous Deployment (CI/CD) pipeline.
#
# 1. Builds the container image.
# 2. Pushes the image to Artifact Registry.
# 3. Deploys the image to Cloud Run, using the custom 'anchor-client-hub' Service Account.

# --- Global Substitutions ---
# IMPORTANT: Replace these placeholder values with your actual project details
# These are the variables that the pipeline will use for execution.
substitutions:
  # The Google Cloud project ID where the resources reside.
  _PROJECT_ID: "anchor-your-practice"
  # The region where the Cloud Run service will be deployed (e.g., us-central1).
  _REGION: "us-central1"
  # The name you want for your Cloud Run service.
  _SERVICE_NAME: "anchor-client-hub-api"
  # The name of your secure, restricted Service Account.
  _SA_NAME: "anchor-client-hub"
  # Artifact Registry Repository name (can be anything descriptive)
  _AR_REPO: "anchor-hub-repository"

steps:

  # 1. Build the Docker Image
  # Builds the image using the Dockerfile located in the source code root.
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      # The target image path in Artifact Registry
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '.'

  # 2. Push the Docker Image to Artifact Registry
  # Pushes the newly built image to the central Artifact Registry repository.
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}'

  # 3. Deploy to Cloud Run using the Custom Service Account
  # Uses the gcloud CLI to deploy the image to Cloud Run.
  # CRITICAL: The --service-account flag ensures deployment uses your restrictive SA.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated' # Strongly recommended for HIPAA-compliant APIs
      - '--service-account'
      # CORRECTED: Ensures the full SA email is constructed properly
      - '${_SA_NAME}@${_PROJECT_ID}.iam.gserviceaccount.com'
      - '--max-instances'
      - '3'
      - '--memory'
      - '1Gi'
